{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Unexpected Http Driver Exception\n"
     ]
    },
    {
     "ename": "OperationalError",
     "evalue": "Error HTTPConnectionPool(host='192.168.0.176', port=8123): Max retries exceeded with url: /?wait_end_of_query=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000259CC3EAE50>, 'Connection to 192.168.0.176 timed out. (connect timeout=10)')) executing HTTP request attempt 1 http://192.168.0.176:8123",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTimeoutError\u001b[0m                              Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\connection.py:174\u001b[0m, in \u001b[0;36mHTTPConnection._new_conn\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    173\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 174\u001b[0m     conn \u001b[39m=\u001b[39m connection\u001b[39m.\u001b[39mcreate_connection(\n\u001b[0;32m    175\u001b[0m         (\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_dns_host, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mport), \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mtimeout, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mextra_kw\n\u001b[0;32m    176\u001b[0m     )\n\u001b[0;32m    178\u001b[0m \u001b[39mexcept\u001b[39;00m SocketTimeout:\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\util\\connection.py:95\u001b[0m, in \u001b[0;36mcreate_connection\u001b[1;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[0;32m     94\u001b[0m \u001b[39mif\u001b[39;00m err \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m---> 95\u001b[0m     \u001b[39mraise\u001b[39;00m err\n\u001b[0;32m     97\u001b[0m \u001b[39mraise\u001b[39;00m socket\u001b[39m.\u001b[39merror(\u001b[39m\"\u001b[39m\u001b[39mgetaddrinfo returns an empty list\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\util\\connection.py:85\u001b[0m, in \u001b[0;36mcreate_connection\u001b[1;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[0;32m     84\u001b[0m     sock\u001b[39m.\u001b[39mbind(source_address)\n\u001b[1;32m---> 85\u001b[0m sock\u001b[39m.\u001b[39mconnect(sa)\n\u001b[0;32m     86\u001b[0m \u001b[39mreturn\u001b[39;00m sock\n",
      "\u001b[1;31mTimeoutError\u001b[0m: timed out",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mConnectTimeoutError\u001b[0m                       Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\connectionpool.py:714\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    713\u001b[0m \u001b[39m# Make the request on the httplib connection object.\u001b[39;00m\n\u001b[1;32m--> 714\u001b[0m httplib_response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_make_request(\n\u001b[0;32m    715\u001b[0m     conn,\n\u001b[0;32m    716\u001b[0m     method,\n\u001b[0;32m    717\u001b[0m     url,\n\u001b[0;32m    718\u001b[0m     timeout\u001b[39m=\u001b[39mtimeout_obj,\n\u001b[0;32m    719\u001b[0m     body\u001b[39m=\u001b[39mbody,\n\u001b[0;32m    720\u001b[0m     headers\u001b[39m=\u001b[39mheaders,\n\u001b[0;32m    721\u001b[0m     chunked\u001b[39m=\u001b[39mchunked,\n\u001b[0;32m    722\u001b[0m )\n\u001b[0;32m    724\u001b[0m \u001b[39m# If we're going to release the connection in ``finally:``, then\u001b[39;00m\n\u001b[0;32m    725\u001b[0m \u001b[39m# the response doesn't need to know about the connection. Otherwise\u001b[39;00m\n\u001b[0;32m    726\u001b[0m \u001b[39m# it will also try to release it and we'll have a double-release\u001b[39;00m\n\u001b[0;32m    727\u001b[0m \u001b[39m# mess.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\connectionpool.py:415\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[1;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[0;32m    414\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m--> 415\u001b[0m         conn\u001b[39m.\u001b[39mrequest(method, url, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mhttplib_request_kw)\n\u001b[0;32m    417\u001b[0m \u001b[39m# We are swallowing BrokenPipeError (errno.EPIPE) since the server is\u001b[39;00m\n\u001b[0;32m    418\u001b[0m \u001b[39m# legitimately able to close the connection after sending a valid response.\u001b[39;00m\n\u001b[0;32m    419\u001b[0m \u001b[39m# With this behaviour, the received response is still readable.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\connection.py:244\u001b[0m, in \u001b[0;36mHTTPConnection.request\u001b[1;34m(self, method, url, body, headers)\u001b[0m\n\u001b[0;32m    243\u001b[0m     headers[\u001b[39m\"\u001b[39m\u001b[39mUser-Agent\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39m=\u001b[39m _get_default_user_agent()\n\u001b[1;32m--> 244\u001b[0m \u001b[39msuper\u001b[39m(HTTPConnection, \u001b[39mself\u001b[39m)\u001b[39m.\u001b[39mrequest(method, url, body\u001b[39m=\u001b[39mbody, headers\u001b[39m=\u001b[39mheaders)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\http\\client.py:1286\u001b[0m, in \u001b[0;36mHTTPConnection.request\u001b[1;34m(self, method, url, body, headers, encode_chunked)\u001b[0m\n\u001b[0;32m   1285\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"Send a complete request to the server.\"\"\"\u001b[39;00m\n\u001b[1;32m-> 1286\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_send_request(method, url, body, headers, encode_chunked)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\http\\client.py:1332\u001b[0m, in \u001b[0;36mHTTPConnection._send_request\u001b[1;34m(self, method, url, body, headers, encode_chunked)\u001b[0m\n\u001b[0;32m   1331\u001b[0m     body \u001b[39m=\u001b[39m _encode(body, \u001b[39m'\u001b[39m\u001b[39mbody\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[1;32m-> 1332\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mendheaders(body, encode_chunked\u001b[39m=\u001b[39mencode_chunked)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\http\\client.py:1281\u001b[0m, in \u001b[0;36mHTTPConnection.endheaders\u001b[1;34m(self, message_body, encode_chunked)\u001b[0m\n\u001b[0;32m   1280\u001b[0m     \u001b[39mraise\u001b[39;00m CannotSendHeader()\n\u001b[1;32m-> 1281\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_send_output(message_body, encode_chunked\u001b[39m=\u001b[39mencode_chunked)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\http\\client.py:1041\u001b[0m, in \u001b[0;36mHTTPConnection._send_output\u001b[1;34m(self, message_body, encode_chunked)\u001b[0m\n\u001b[0;32m   1040\u001b[0m \u001b[39mdel\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_buffer[:]\n\u001b[1;32m-> 1041\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msend(msg)\n\u001b[0;32m   1043\u001b[0m \u001b[39mif\u001b[39;00m message_body \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m   1044\u001b[0m \n\u001b[0;32m   1045\u001b[0m     \u001b[39m# create a consistent interface to message_body\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\http\\client.py:979\u001b[0m, in \u001b[0;36mHTTPConnection.send\u001b[1;34m(self, data)\u001b[0m\n\u001b[0;32m    978\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mauto_open:\n\u001b[1;32m--> 979\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mconnect()\n\u001b[0;32m    980\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\connection.py:205\u001b[0m, in \u001b[0;36mHTTPConnection.connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    204\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconnect\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[1;32m--> 205\u001b[0m     conn \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_new_conn()\n\u001b[0;32m    206\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_prepare_conn(conn)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\connection.py:179\u001b[0m, in \u001b[0;36mHTTPConnection._new_conn\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    178\u001b[0m \u001b[39mexcept\u001b[39;00m SocketTimeout:\n\u001b[1;32m--> 179\u001b[0m     \u001b[39mraise\u001b[39;00m ConnectTimeoutError(\n\u001b[0;32m    180\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[0;32m    181\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mConnection to \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m timed out. (connect timeout=\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m)\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m    182\u001b[0m         \u001b[39m%\u001b[39m (\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mhost, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mtimeout),\n\u001b[0;32m    183\u001b[0m     )\n\u001b[0;32m    185\u001b[0m \u001b[39mexcept\u001b[39;00m SocketError \u001b[39mas\u001b[39;00m e:\n",
      "\u001b[1;31mConnectTimeoutError\u001b[0m: (<urllib3.connection.HTTPConnection object at 0x00000259CC3EAE50>, 'Connection to 192.168.0.176 timed out. (connect timeout=10)')",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mMaxRetryError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\clickhouse_connect\\driver\\httpclient.py:409\u001b[0m, in \u001b[0;36mHttpClient._raw_request\u001b[1;34m(self, data, params, headers, method, retries, stream, server_wait, fields, error_handler)\u001b[0m\n\u001b[0;32m    408\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 409\u001b[0m     response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mhttp\u001b[39m.\u001b[39mrequest(method, url, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[0;32m    410\u001b[0m \u001b[39mexcept\u001b[39;00m HTTPError \u001b[39mas\u001b[39;00m ex:\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\request.py:78\u001b[0m, in \u001b[0;36mRequestMethods.request\u001b[1;34m(self, method, url, fields, headers, **urlopen_kw)\u001b[0m\n\u001b[0;32m     77\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m---> 78\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mrequest_encode_body(\n\u001b[0;32m     79\u001b[0m         method, url, fields\u001b[39m=\u001b[39mfields, headers\u001b[39m=\u001b[39mheaders, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39murlopen_kw\n\u001b[0;32m     80\u001b[0m     )\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\request.py:170\u001b[0m, in \u001b[0;36mRequestMethods.request_encode_body\u001b[1;34m(self, method, url, fields, headers, encode_multipart, multipart_boundary, **urlopen_kw)\u001b[0m\n\u001b[0;32m    168\u001b[0m extra_kw\u001b[39m.\u001b[39mupdate(urlopen_kw)\n\u001b[1;32m--> 170\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39murlopen(method, url, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mextra_kw)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\poolmanager.py:376\u001b[0m, in \u001b[0;36mPoolManager.urlopen\u001b[1;34m(self, method, url, redirect, **kw)\u001b[0m\n\u001b[0;32m    375\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m--> 376\u001b[0m     response \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39murlopen(method, u\u001b[39m.\u001b[39mrequest_uri, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkw)\n\u001b[0;32m    378\u001b[0m redirect_location \u001b[39m=\u001b[39m redirect \u001b[39mand\u001b[39;00m response\u001b[39m.\u001b[39mget_redirect_location()\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\connectionpool.py:826\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    823\u001b[0m     log\u001b[39m.\u001b[39mwarning(\n\u001b[0;32m    824\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mRetrying (\u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m) after connection broken by \u001b[39m\u001b[39m'\u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m: \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m, retries, err, url\n\u001b[0;32m    825\u001b[0m     )\n\u001b[1;32m--> 826\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39murlopen(\n\u001b[0;32m    827\u001b[0m         method,\n\u001b[0;32m    828\u001b[0m         url,\n\u001b[0;32m    829\u001b[0m         body,\n\u001b[0;32m    830\u001b[0m         headers,\n\u001b[0;32m    831\u001b[0m         retries,\n\u001b[0;32m    832\u001b[0m         redirect,\n\u001b[0;32m    833\u001b[0m         assert_same_host,\n\u001b[0;32m    834\u001b[0m         timeout\u001b[39m=\u001b[39mtimeout,\n\u001b[0;32m    835\u001b[0m         pool_timeout\u001b[39m=\u001b[39mpool_timeout,\n\u001b[0;32m    836\u001b[0m         release_conn\u001b[39m=\u001b[39mrelease_conn,\n\u001b[0;32m    837\u001b[0m         chunked\u001b[39m=\u001b[39mchunked,\n\u001b[0;32m    838\u001b[0m         body_pos\u001b[39m=\u001b[39mbody_pos,\n\u001b[0;32m    839\u001b[0m         \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mresponse_kw\n\u001b[0;32m    840\u001b[0m     )\n\u001b[0;32m    842\u001b[0m \u001b[39m# Handle redirect?\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\connectionpool.py:798\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    796\u001b[0m     e \u001b[39m=\u001b[39m ProtocolError(\u001b[39m\"\u001b[39m\u001b[39mConnection aborted.\u001b[39m\u001b[39m\"\u001b[39m, e)\n\u001b[1;32m--> 798\u001b[0m retries \u001b[39m=\u001b[39m retries\u001b[39m.\u001b[39mincrement(\n\u001b[0;32m    799\u001b[0m     method, url, error\u001b[39m=\u001b[39me, _pool\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m, _stacktrace\u001b[39m=\u001b[39msys\u001b[39m.\u001b[39mexc_info()[\u001b[39m2\u001b[39m]\n\u001b[0;32m    800\u001b[0m )\n\u001b[0;32m    801\u001b[0m retries\u001b[39m.\u001b[39msleep()\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\urllib3\\util\\retry.py:592\u001b[0m, in \u001b[0;36mRetry.increment\u001b[1;34m(self, method, url, response, error, _pool, _stacktrace)\u001b[0m\n\u001b[0;32m    591\u001b[0m \u001b[39mif\u001b[39;00m new_retry\u001b[39m.\u001b[39mis_exhausted():\n\u001b[1;32m--> 592\u001b[0m     \u001b[39mraise\u001b[39;00m MaxRetryError(_pool, url, error \u001b[39mor\u001b[39;00m ResponseError(cause))\n\u001b[0;32m    594\u001b[0m log\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mIncremented Retry for (url=\u001b[39m\u001b[39m'\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m): \u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m\"\u001b[39m, url, new_retry)\n",
      "\u001b[1;31mMaxRetryError\u001b[0m: HTTPConnectionPool(host='192.168.0.176', port=8123): Max retries exceeded with url: /?wait_end_of_query=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000259CC3EAE50>, 'Connection to 192.168.0.176 timed out. (connect timeout=10)'))",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[1;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\julio.lima\\Desktop\\PROJETO_PRE_PEDIDOS\\PROJETO_PRE_PEDIDO.ipynb Cell 1\u001b[0m line \u001b[0;36m9\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W0sZmlsZQ%3D%3D?line=5'>6</a>\u001b[0m CLICKHOUSE_USER \u001b[39m=\u001b[39m \u001b[39m'\u001b[39m\u001b[39myuri\u001b[39m\u001b[39m'\u001b[39m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W0sZmlsZQ%3D%3D?line=6'>7</a>\u001b[0m CLICKHOUSE_PASSWORD \u001b[39m=\u001b[39m \u001b[39m'\u001b[39m\u001b[39mRmonTEiS\u001b[39m\u001b[39m'\u001b[39m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W0sZmlsZQ%3D%3D?line=8'>9</a>\u001b[0m client \u001b[39m=\u001b[39m clickhouse_connect\u001b[39m.\u001b[39mget_client(\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W0sZmlsZQ%3D%3D?line=9'>10</a>\u001b[0m     host\u001b[39m=\u001b[39mCLICKHOUSE_HOSTNAME, port\u001b[39m=\u001b[39m\u001b[39m8123\u001b[39m, username\u001b[39m=\u001b[39mCLICKHOUSE_USER, password\u001b[39m=\u001b[39mCLICKHOUSE_PASSWORD)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W0sZmlsZQ%3D%3D?line=11'>12</a>\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mconnected to \u001b[39m\u001b[39m\"\u001b[39m \u001b[39m+\u001b[39m CLICKHOUSE_HOSTNAME \u001b[39m+\u001b[39m \u001b[39m\"\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W0sZmlsZQ%3D%3D?line=13'>14</a>\u001b[0m QUERY \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mselect \u001b[39m\u001b[39m\\\u001b[39;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W0sZmlsZQ%3D%3D?line=14'>15</a>\u001b[0m \u001b[39mA.codprodrelacionado, \u001b[39m\u001b[39m\\\u001b[39;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W0sZmlsZQ%3D%3D?line=15'>16</a>\u001b[0m \u001b[39mfrom analytics. _analitica A \u001b[39m\u001b[39m\\\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W0sZmlsZQ%3D%3D?line=22'>23</a>\u001b[0m \u001b[39mand A.cnpjdestinatario <> \u001b[39m\u001b[39m'\u001b[39m\u001b[39m07608233000110\u001b[39m\u001b[39m'\u001b[39m\u001b[39m \u001b[39m\u001b[39m\\\u001b[39;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W0sZmlsZQ%3D%3D?line=23'>24</a>\u001b[0m \u001b[39mand A.operacao2= \u001b[39m\u001b[39m'\u001b[39m\u001b[39mVENDA\u001b[39m\u001b[39m'\u001b[39m\u001b[39m\"\u001b[39m\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\clickhouse_connect\\__init__.py:8\u001b[0m, in \u001b[0;36mget_client\u001b[1;34m(**kwargs)\u001b[0m\n\u001b[0;32m      7\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mget_client\u001b[39m(\u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m----> 8\u001b[0m     \u001b[39mreturn\u001b[39;00m create_client(\u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\clickhouse_connect\\driver\\__init__.py:110\u001b[0m, in \u001b[0;36mcreate_client\u001b[1;34m(host, username, password, database, interface, port, secure, dsn, settings, generic_args, **kwargs)\u001b[0m\n\u001b[0;32m    108\u001b[0m                     name \u001b[39m=\u001b[39m name[\u001b[39m3\u001b[39m:]\n\u001b[0;32m    109\u001b[0m                 settings[name] \u001b[39m=\u001b[39m value\n\u001b[1;32m--> 110\u001b[0m     \u001b[39mreturn\u001b[39;00m HttpClient(interface, host, port, username, password, database, settings\u001b[39m=\u001b[39msettings, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[0;32m    111\u001b[0m \u001b[39mraise\u001b[39;00m ProgrammingError(\u001b[39mf\u001b[39m\u001b[39m'\u001b[39m\u001b[39mUnrecognized client type \u001b[39m\u001b[39m{\u001b[39;00minterface\u001b[39m}\u001b[39;00m\u001b[39m'\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\clickhouse_connect\\driver\\httpclient.py:140\u001b[0m, in \u001b[0;36mHttpClient.__init__\u001b[1;34m(self, interface, host, port, username, password, database, compress, query_limit, query_retries, connect_timeout, send_receive_timeout, client_name, verify, ca_cert, client_cert, client_cert_key, session_id, settings, pool_mgr, http_proxy, https_proxy, server_host_name, apply_server_timezone)\u001b[0m\n\u001b[0;32m    137\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m    138\u001b[0m     compression \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m--> 140\u001b[0m \u001b[39msuper\u001b[39m()\u001b[39m.\u001b[39m\u001b[39m__init__\u001b[39m(database\u001b[39m=\u001b[39mdatabase,\n\u001b[0;32m    141\u001b[0m                  uri\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39murl,\n\u001b[0;32m    142\u001b[0m                  query_limit\u001b[39m=\u001b[39mquery_limit,\n\u001b[0;32m    143\u001b[0m                  query_retries\u001b[39m=\u001b[39mquery_retries,\n\u001b[0;32m    144\u001b[0m                  server_host_name\u001b[39m=\u001b[39mserver_host_name,\n\u001b[0;32m    145\u001b[0m                  apply_server_timezone\u001b[39m=\u001b[39mapply_server_timezone)\n\u001b[0;32m    146\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mparams \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_validate_settings(ch_settings)\n\u001b[0;32m    147\u001b[0m comp_setting \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_setting_status(\u001b[39m'\u001b[39m\u001b[39menable_http_compression\u001b[39m\u001b[39m'\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\clickhouse_connect\\driver\\client.py:60\u001b[0m, in \u001b[0;36mClient.__init__\u001b[1;34m(self, database, query_limit, uri, query_retries, server_host_name, apply_server_timezone)\u001b[0m\n\u001b[0;32m     57\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mserver_host_name \u001b[39m=\u001b[39m server_host_name\n\u001b[0;32m     58\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mserver_tz \u001b[39m=\u001b[39m pytz\u001b[39m.\u001b[39mUTC\n\u001b[0;32m     59\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mserver_version, server_tz \u001b[39m=\u001b[39m \\\n\u001b[1;32m---> 60\u001b[0m     \u001b[39mtuple\u001b[39m(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcommand(\u001b[39m'\u001b[39m\u001b[39mSELECT version(), timezone()\u001b[39m\u001b[39m'\u001b[39m, use_database\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m))\n\u001b[0;32m     61\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m     62\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mserver_tz \u001b[39m=\u001b[39m pytz\u001b[39m.\u001b[39mtimezone(server_tz)\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\clickhouse_connect\\driver\\httpclient.py:331\u001b[0m, in \u001b[0;36mHttpClient.command\u001b[1;34m(self, cmd, parameters, data, settings, use_database, external_data)\u001b[0m\n\u001b[0;32m    328\u001b[0m params\u001b[39m.\u001b[39mupdate(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_validate_settings(settings \u001b[39mor\u001b[39;00m {}))\n\u001b[0;32m    330\u001b[0m method \u001b[39m=\u001b[39m \u001b[39m'\u001b[39m\u001b[39mPOST\u001b[39m\u001b[39m'\u001b[39m \u001b[39mif\u001b[39;00m payload \u001b[39mor\u001b[39;00m fields \u001b[39melse\u001b[39;00m \u001b[39m'\u001b[39m\u001b[39mGET\u001b[39m\u001b[39m'\u001b[39m\n\u001b[1;32m--> 331\u001b[0m response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_raw_request(payload, params, headers, method, fields\u001b[39m=\u001b[39mfields)\n\u001b[0;32m    332\u001b[0m \u001b[39mif\u001b[39;00m response\u001b[39m.\u001b[39mdata:\n\u001b[0;32m    333\u001b[0m     \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\julio.lima\\AppData\\Local\\anaconda3\\Lib\\site-packages\\clickhouse_connect\\driver\\httpclient.py:420\u001b[0m, in \u001b[0;36mHttpClient._raw_request\u001b[1;34m(self, data, params, headers, method, retries, stream, server_wait, fields, error_handler)\u001b[0m\n\u001b[0;32m    418\u001b[0m             \u001b[39mcontinue\u001b[39;00m\n\u001b[0;32m    419\u001b[0m     logger\u001b[39m.\u001b[39mwarning(\u001b[39m'\u001b[39m\u001b[39mUnexpected Http Driver Exception\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[1;32m--> 420\u001b[0m     \u001b[39mraise\u001b[39;00m OperationalError(\u001b[39mf\u001b[39m\u001b[39m'\u001b[39m\u001b[39mError \u001b[39m\u001b[39m{\u001b[39;00mex\u001b[39m}\u001b[39;00m\u001b[39m executing HTTP request attempt \u001b[39m\u001b[39m{\u001b[39;00mattempts\u001b[39m}\u001b[39;00m\u001b[39m \u001b[39m\u001b[39m{\u001b[39;00m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39murl\u001b[39m}\u001b[39;00m\u001b[39m'\u001b[39m) \u001b[39mfrom\u001b[39;00m \u001b[39mex\u001b[39;00m\n\u001b[0;32m    421\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    422\u001b[0m     \u001b[39mif\u001b[39;00m query_session:\n",
      "\u001b[1;31mOperationalError\u001b[0m: Error HTTPConnectionPool(host='192.168.0.176', port=8123): Max retries exceeded with url: /?wait_end_of_query=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000259CC3EAE50>, 'Connection to 192.168.0.176 timed out. (connect timeout=10)')) executing HTTP request attempt 1 http://192.168.0.176:8123"
     ]
    }
   ],
   "source": [
    "import clickhouse_connect\n",
    "import sys\n",
    "import json\n",
    "import pandas as pd\n",
    "\n",
    "CLICKHOUSE_HOSTNAME = '192.168.0.176'\n",
    "CLICKHOUSE_USER = 'yuri'\n",
    "CLICKHOUSE_PASSWORD = 'RmonTEiS'\n",
    "\n",
    "client = clickhouse_connect.get_client(\n",
    "    host=CLICKHOUSE_HOSTNAME, port=8123, username=CLICKHOUSE_USER, password=CLICKHOUSE_PASSWORD)\n",
    "\n",
    "print(\"connected to \" + CLICKHOUSE_HOSTNAME + \"\\n\")\n",
    "\n",
    "QUERY = \"select \\\n",
    "A.codprodrelacionado, \\\n",
    "from analytics. _analitica A \\\n",
    "WHERE 1=1 \\\n",
    "and data between toDate(now()) - INTERVAL 90 DAY and toDate(now()) \\\n",
    "--and data toDate('22-09-2023') \\\n",
    "and A.emitente <> '1' \\\n",
    "and A.uf_destinatario IN ('CE') \\\n",
    "and A.cnpjdestinatario <> '07146710000254' \\\n",
    "and A.cnpjdestinatario <> '07608233000110' \\\n",
    "and A.operacao2= 'VENDA'\"\n",
    "\n",
    "with client.query_df_stream(QUERY) as result:\n",
    "    for row in result:\n",
    "        print(row)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "DatabaseError",
     "evalue": "DPI-1047: Cannot locate a 64-bit Oracle Client library: \"C:\\app\\client\\Administrador\\product\\19.0.0\\client_1\\bin\\oci.dll is not the correct architecture\". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mDatabaseError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\julio.lima\\Desktop\\PROJETO_PRE_PEDIDOS\\PROJETO_PRE_PEDIDO.ipynb Cell 2\u001b[0m line \u001b[0;36m4\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W1sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mcx_Oracle\u001b[39;00m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W1sZmlsZQ%3D%3D?line=2'>3</a>\u001b[0m \u001b[39m# cx_Oracle.init_oracle_client(lib_dir=\"C:\\\\oracle\\\\instantclient_21_11\")\u001b[39;00m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W1sZmlsZQ%3D%3D?line=3'>4</a>\u001b[0m cx_Oracle\u001b[39m.\u001b[39minit_oracle_client(lib_dir\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mC:\u001b[39m\u001b[39m\\\\\u001b[39;00m\u001b[39mOracle_Cliente_32Bits\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W1sZmlsZQ%3D%3D?line=4'>5</a>\u001b[0m dsn \u001b[39m=\u001b[39m cx_Oracle\u001b[39m.\u001b[39mmakedsn(\u001b[39m'\u001b[39m\u001b[39m192.168.0.125\u001b[39m\u001b[39m'\u001b[39m, \u001b[39m'\u001b[39m\u001b[39m1521\u001b[39m\u001b[39m'\u001b[39m, \u001b[39m'\u001b[39m\u001b[39mORCL\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/julio.lima/Desktop/PROJETO_PRE_PEDIDOS/PROJETO_PRE_PEDIDO.ipynb#W1sZmlsZQ%3D%3D?line=6'>7</a>\u001b[0m conexao \u001b[39m=\u001b[39m cx_Oracle\u001b[39m.\u001b[39mconnect(\u001b[39m'\u001b[39m\u001b[39mLAREDOBI\u001b[39m\u001b[39m'\u001b[39m, \u001b[39m'\u001b[39m\u001b[39mlaredo01bi\u001b[39m\u001b[39m'\u001b[39m, \u001b[39m'\u001b[39m\u001b[39m192.168.0.125:1521/ORCL\u001b[39m\u001b[39m'\u001b[39m)\n",
      "\u001b[1;31mDatabaseError\u001b[0m: DPI-1047: Cannot locate a 64-bit Oracle Client library: \"C:\\app\\client\\Administrador\\product\\19.0.0\\client_1\\bin\\oci.dll is not the correct architecture\". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help"
     ]
    }
   ],
   "source": [
    "import cx_Oracle\n",
    "\n",
    "# cx_Oracle.init_oracle_client(lib_dir=\"C:\\\\oracle\\\\instantclient_21_11\")\n",
    "cx_Oracle.init_oracle_client(lib_dir=\"C:\\\\Oracle_Cliente_32Bits\")\n",
    "\n",
    "dsn = cx_Oracle.makedsn('192.168.0.125', '1521', 'ORCL')\n",
    "\n",
    "conexao = cx_Oracle.connect('LAREDOBI', 'laredo01bi', '192.168.0.125:1521/ORCL')\n",
    "\n",
    "print(\"Conectado ao banco de dados em  192.168.0.125\")\n",
    "\n",
    "cursor = conexao.cursor()\n",
    "\n",
    "consulta = \"\"\"SELECT \\\n",
    "V.CODPROD AS codprodrelacionado, \\\n",
    "V.CNPJ AS cnpjdestinatario,  \\\n",
    "V.DTSAIDA AS data, \\\n",
    "V.NUMPED AS danfe,\\\n",
    "V.FATURAMENTO AS valor_total, \\\n",
    "V.QT AS quantidade, \\\n",
    "V.PVENDA AS valor_unitario, \\\n",
    "V.Produto AS produtolaredo, \\\n",
    "V.CODFILIAL \\\n",
    "FROM( \\\n",
    "SELECT \\\n",
    "V.CODFILIAL, \\\n",
    "V.FILIAL,  \\\n",
    "V.CODCLI, \\\n",
    "V.RCA, \\\n",
    "V.CODPROD, \\\n",
    "V.DTSAIDA, \\\n",
    "V.CIDADE, \\\n",
    "V.CONDVENDA, \\\n",
    "V.\"Cod Supervisor\", \\\n",
    "V.NUMPED, \\\n",
    "V.NUMREGIAO, \\\n",
    "V.CODCATEGORIA, \\\n",
    "V.QT*V.PVENDA FATURAMENTO, \\\n",
    "V.CODFORNEC, \\\n",
    "V.DATA, \\\n",
    "V.QT, \\\n",
    "V.PESOBRUTO, \\\n",
    "V.\"Produto\" AS Produto, \\\n",
    "V.PVENDA, \\\n",
    "REPLACE(REPLACE(REPLACE(V.CNPJ,'.', ''),'-', ''),'/', '') AS CNPJ, \\\n",
    "CASE WHEN V.CODFILIAL IN(8) THEN V.VLCUSTOREAL * 1.15 ELSE V.VLCUSTOREAL END AS VLCUSTOREAL \\\n",
    "FROM LAREDO.V_VENDASANALITICA_2 V \\\n",
    "WHERE \\\n",
    "V.CONDVENDA = '1' AND \\\n",
    "V.\"Cod Supervisor\" NOT IN  (13, 14, 1, 2, 62, 3, 4)\\\n",
    "AND V.CODFILIAL IN('1','2','22','3','4','5','6','7','8') \\\n",
    "AND V.DTSAIDA = TO_DATE('25/09/2023', 'DD/MM/YYYY')\\\n",
    " ) V\"\"\"\n",
    "\n",
    "cursor.execute(consulta)\n",
    "\n",
    "resultados = cursor.fetchall()\n",
    "\n",
    "dfo = pd.DataFrame(resultados)\n",
    "\n",
    "cursor.close()\n",
    "conexao.close()\n",
    "\n",
    "dfo.head(30)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
